### ISSUE TITLE
Leaflet v1.4.0 removed _drawnLayers

### ISSUE THREAD

**Issue by pioka2** [Oliv/leaflet-polycolor#2]
Hi all,

my code runs with 1.3.4 fine but not with newer versions.

As written in the changelog Leaflet removed in 1.4.0 the "_unused_ __drawnLayers object_". 

Is there a workaround or a bug fix for leaflet-polycolor? 

Thanks and best regards

**Comment by 16bc** [comment]
Hi,
i fixed this by changing the **15 line** in **/src/leaflet-polycolor.js**
from
`this._drawnLayers[layer._leaflet_id] = layer `
to
`this._layers[layer._leaflet_id] = layer;`

**Comment by lancemitchell** [comment]
I got the same issue. I hacked the source to apply the fix, but really this fix should be a MAJOR bugfix released. Its been over 30 days?

**Comment by Oliv** [comment]
Hi, finally merged, I updated the version to 1.0.0 in npm
