### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'x')

### ISSUE THREAD

**Issue by isuke01** [Oliv/leaflet-polycolor#7]
Hi,

I'm trying to use the plugin with:
`@vue-leaflet/vue-leaflet`: **0.6.1**
`leaflet`: **1.8.0**

It renders the line correctly, but when I try to move map I'm getting hundreds of errors: 
```js
Bounds.js:119 Uncaught TypeError: Cannot read properties of undefined (reading 'x')
    at Bounds.contains (Bounds.js:119:15)
    at NewClass._containsPoint (Polyline.js:310:42)
    at NewClass._handleMouseHover (Canvas.js:398:43)
    at NewClass._onMouseMove (Canvas.js:374:8)
    at HTMLCanvasElement.handler (DomEvent.js:108:13)
```
I'm using it exactly like in example.
Any clue? 

Edit.
Looks like it is issue with the `@vue-leaflet/vue-leaflet`  https://github.com/vue-leaflet/vue-leaflet/issues/212

**Comment by Oliv** [comment]
Hi, I'm gonna look into this, it may be because of leaflet 1.8

Edit: It is not a problem with leaflet 1.8 so vue must be the culprit, have you a reproductible use case ?

**Comment by Oliv** [comment]
Hello,

Could you please try again with the new version please ?

Regards

**Comment by vesper8** [comment]
Still having this issue with the latest release. What finally worked for me was adding `:use-global-leaflet="false"` to my `l-map` tag and importing `L` with `import * as L from 'leaflet/dist/leaflet-src.esm';`

Then that error went away and everything works.

**Comment by Oliv** [comment]
That's nice you managed to get this issue fixed, I will update the readme to explain this use case.

Thanks a lot
