### ISSUE TITLE
Option to disable gradient?

### ISSUE THREAD

**Issue by isuke01** [Oliv/leaflet-polycolor#8]
Hi, I need option to disable the gradient.

At this point I copy whole code into different file and I extended the function `_getStrokeGradient`
with simple code like: 
```js
const disableGrandient = options.disableGrandient || false
const gradientEndRGB = options.colors[ disableGrandient ? j : j + 1 ] || options.color;
```
And simply by that I'm able to write line without gradient :)

But it would be nice to have that option out of the box in the plugin, and probably implemented a bit better :)

**Comment by Oliv** [comment]
Hello, just pushed the version 1.1.1 witch adds a new useGradient option
